beauty_morph_deltas = "beauty.mdeltas"
face_subsets = ["makeup.bsm2"]

draw_order = [ "retouch", "makeup", "TriMat", "!glfx_UPDATE_BG", "Q0"]

#For avoid zfight
adjust_znear=0.0
adjust_zfar=0.0

[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
tex_softlight=0
tex_makeup=3

[materials.makeup]
vs = "makeup.vert"
fs = "makeup.frag"
blend = "premul_alpha"
backfaces = false
colorwrite = true
zwrite = false
shadow = false
onface = true
face_subset = "makeup.bsm2"
[materials.makeup.samplers]
tex_highlight="flare1.ktx"
tex_makeup=1
tex_eyebrows=2

[materials.TriMat]
vs = "fstri.vert"
fs = "lut.frag"
blend = "off"
backfaces = true
shadow = false
ztest = false
zwrite = false
samplers = {}

[materials.Q0]
vs = "lips.vert"
fs = "lips.frag"
blend = "alpha"
backfaces = true
colorwrite = true
zwrite = false
ztest = false
shadow = false
samplers = {}
