warp_mesh = "CubemapEverestMorph.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', 'cut', 'CubemapEverest', 'TriMat', 'TriAndroid']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="REDMASK_v3_256.png"
lookupTexTeeth="teeth_high.png"
lookupTexEyes="eyes_high.png"
tex_softLight="SOFT_princess_256.png"
tex_normalMakeup="facemat_BaseColor.png"
tex_highlight="39.png"

# Cut
[materials.cut]
vs = "cut.vert"
fs = "cut.frag"
blend = "off"
backfaces = false
colorwrite = false
zwrite = true
shadow = false
samplers = {}

# PBR
[materials.CubemapEverest]
vs = "cubemapeverest.vert"
fs = "cubemapeverest.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = true
[materials.CubemapEverest.samplers]
tex_diffuse="CubemapEverest_BaseColor.png"
tex_normal="CubemapEverest_Normal.png"
tex_metallic="CubemapEverest_Metallic.png"
tex_roughness="CubemapEverest_Roughness.png"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"

[materials.TriMat]
vs = "bg.vert"
fs = "bg.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = false
shadow = false
samplers = { tex_env="env.ktx" }

[materials.TriAndroid]
vs = "bg_a.vert"
fs = "bg.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply"
backfaces = false
colorwrite = true
zwrite = false
shadow = false
samplers = { tex_env="env.ktx" }