// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from recognizer.djinni

#import "BNBFeatureId.h"
#import "BNBFrameData.h"
#import <Foundation/Foundation.h>
@class BNBActiveRecognizer;


@interface BNBActiveRecognizer : NSObject

+ (nullable BNBActiveRecognizer *)create;

- (void)setFeatures:(BNBFeatureId)features;

- (void)setCameraSize:(int32_t)width
               height:(int32_t)height;

- (void)setFaceOrientation:(int32_t)roll;

/** sets maximum allowed face results, if face tracking feature is present */
- (void)setMaxFaces:(int32_t)num;

- (void)setOfflineMode:(BOOL)on;

/**
 * Set flag which enable NN-dependent features. True by default, if device compatible with NN player
 * When this flag is false, recognizer will skip NN-dependent features during set_features call.
 * In case when device have no NN player support (is_device_nn_compatible return false),
 * setting enable to true have no any effect
 */
- (void)setNnEnable:(BOOL)enable;

- (BOOL)getNnEnable;

/**
 * Check if device compatible with NN player.
 * This call will return correct information only after gl context will be created
 */
- (BOOL)isDeviceNnCompatible;

- (void)pushCameraFrame:(nullable BNBFrameData *)inputFrameData;

- (BOOL)popFrameData:(nullable BNBFrameData *)outputFrameData;

/** start the thread */
- (void)start;

/** pause + clear */
- (void)stop;

/** clear input and output buffers and pipeline state */
- (void)clear;

@end
