// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from recognizer.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, BNBFeatureId)
{
    BNBFeatureIdFrx,
    BNBFeatureIdActionUnits,
    BNBFeatureIdBackground,
    BNBFeatureIdHair,
    BNBFeatureIdEyes,
    BNBFeatureIdSkin,
    BNBFeatureIdLips,
    BNBFeatureIdOcclussion,
    BNBFeatureIdGlasses,
    BNBFeatureIdAcne,
    BNBFeatureIdHandSkelet,
    BNBFeatureIdFrameBrightness,
};
