// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from types.djinni

#import "BNBAcneRegions.h"
#import "BNBActionUnitsData.h"
#import "BNBPixelFormat.h"
#import "BNBTransformedMaskByte.h"
#import "BNBTransformedMaskGpu.h"
#import "BanubaEffectPlayer/BNBFullImageData.h"
#import <Foundation/Foundation.h>
@class BNBFrameData;
@class BNBFrxRecognitionResult;


/**
 *getters throw exceptions when data are not available
 *android NNs usually output gpu masks
 */
@interface BNBFrameData : NSObject

- (nonnull NSArray<NSNumber *> *)getFullImgTransform;

/** Get frx_recognition_result or null if not exists */
- (nullable BNBFrxRecognitionResult *)getFrxRecognitionResult;

- (nonnull BNBActionUnitsData *)getActionUnits;

- (nonnull BNBAcneRegions *)getAcneRegions;

- (BOOL)getIsSmile;

- (BOOL)getIsMouthOpen;

- (BOOL)getIsBrowsRaised;

- (BOOL)getIsBrowsShifted;

- (BOOL)getIsWearGlasses;

- (float)getIsMale;

- (float)getRuler;

- (nonnull BNBTransformedMaskByte *)getBackground;

- (nonnull BNBTransformedMaskGpu *)getBackgroundGpu;

- (nonnull BNBTransformedMaskByte *)getHair;

- (nonnull BNBTransformedMaskGpu *)getHairGpu;

- (nonnull BNBTransformedMaskByte *)getSkin;

- (nonnull BNBTransformedMaskGpu *)getSkinGpu;

- (nonnull BNBTransformedMaskByte *)getLips;

- (nonnull BNBTransformedMaskGpu *)getLipsGpu;

- (nonnull BNBTransformedMaskByte *)getOcclusion;

- (nonnull BNBTransformedMaskByte *)getBody;

+ (nullable BNBFrameData *)makeEmpty;

- (void)addFullImg:(nonnull BNBFullImageData *)img;

- (void)addBackground:(nonnull BNBTransformedMaskByte *)mask;

+ (nullable BNBFrameData *)makeFromYuv:(int32_t)width
                                height:(int32_t)height
                               yBuffer:(nonnull NSData *)yBuffer
                            yRowStride:(int32_t)yRowStride
                          yPixelStride:(int32_t)yPixelStride
                               uBuffer:(nonnull NSData *)uBuffer
                            uRowStride:(int32_t)uRowStride
                          uPixelStride:(int32_t)uPixelStride
                               vBuffer:(nonnull NSData *)vBuffer
                            vRowStride:(int32_t)vRowStride
                          vPixelStride:(int32_t)vPixelStride
                           frameNumber:(int64_t)frameNumber;

+ (nullable BNBFrameData *)makeFromBpc8:(int32_t)width
                                 height:(int32_t)height
                                 format:(BNBPixelFormat)format
                             bpc8Buffer:(nonnull NSData *)bpc8Buffer
                            frameNumber:(int64_t)frameNumber;

@end
