// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from utils.djinni

#import "BNBSeverityLevel.h"
#import <Foundation/Foundation.h>
@protocol BNBLogRecordCallback;


@interface BNBUtilityManager : NSObject

+ (void)initialize:(nonnull NSArray<NSString *> *)resourcePaths
       clientToken:(nonnull NSString *)clientToken;

+ (void)release;

/** Diagnostic crash. Use this to check you crash analytics systems.  */
+ (void)diagnosticCrash;

/**
 * Get information about CPU capabilities. Mainly for usage on Android
 * @return JSON-string describing CPU capabilties
 */
+ (nonnull NSString *)cpuEnv;

/**
 * Check if device have high-end SoC.
 * Only Android supported now, for other platforms always return true
 * @return true if device is fast
 */
+ (BOOL)isFastDevice;

+ (void)setLogLevel:(BNBSeverityLevel)level;

/**
 * Set callback to recieve log events from Banuba SDK.
 * @param cb Callback
 * @param lvl recieve logs with specified and higher levels
 */
+ (void)setLogRecordCallback:(nullable id<BNBLogRecordCallback>)cb
                         lvl:(BNBSeverityLevel)lvl;

@end
