// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from scene.djinni

#import <Foundation/Foundation.h>


@interface BNBFaceMorphing : NSObject

- (void)setFaceWeight:(float)value;

- (float)getFaceWeight;

- (void)setNoseWeight:(float)value;

- (float)getNoseWeight;

- (void)setEyesWeight:(float)value;

- (float)getEyesWeight;

@end
