// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from effect_player.djinni

#import "BNBPixelRect.h"
#import <Foundation/Foundation.h>

@interface BNBProcessImageParams : NSObject
- (nonnull instancetype)initWithAcneProcessing:(BOOL)acneProcessing
                                 acneUserAreas:(nullable NSArray<BNBPixelRect *> *)acneUserAreas;
+ (nonnull instancetype)processImageParamsWithAcneProcessing:(BOOL)acneProcessing
                                               acneUserAreas:(nullable NSArray<BNBPixelRect *> *)acneUserAreas;

/** Set this param to force running of acne processing feature */
@property (nonatomic, readonly) BOOL acneProcessing;

/** User-defined acne areas to mask, rectangles are in input image coordinate space */
@property (nonatomic, readonly, nullable) NSArray<BNBPixelRect *> * acneUserAreas;

@end
