warp_mesh = "morth.bsm2"
msaa = 1
shadowmap_size = 512
adjust_znear = 150
draw_order = ['retouch', '!glfx_WARP_IMAGE', 'glass', 'PineappleGlasses']

# Retouch
[materials.retouch]
vs = "retouch.vert"
fs = "retouch.frag"
blend = "off" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
onface = true
mouth = true
[materials.retouch.samplers]
selection_tex="REDMASK_v3_256.png"
lookupTexTeeth="TEETH_high.png"
lookupTexEyes="EYES_high.png"
tex_softLight="soft_dark_eyes_256.png"
tex_normalMakeup="50s_256x512.png"
tex_highlight="FLARE_37_768.png"

# PBR
[materials.glass]
vs = "glass.vert"
fs = "glass.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.glass.samplers]
tex_diffuse="PineappleGlasses_Base_Color.ktx"
tex_normal="PineappleGlasses_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="PineappleGlasses_MRAO.ktx"

# PBR
[materials.PineappleGlasses]
vs = "pineappleglasses.vert"
fs = "pineappleglasses.frag"
blend = "alpha" # "alpha", "premul_alpha", "screen", "add", "multiply", "coverage", "off"
backfaces = false
colorwrite = true
zwrite = true
shadow = false
[materials.PineappleGlasses.samplers]
tex_diffuse="PineappleGlasses_Base_Color.ktx"
tex_normal="PineappleGlasses_Normal.ktx"
tex_brdf="brdf.ktx"
tex_ibl_diff="ibl_diff.ktx"
tex_ibl_spec="ibl_spec.ktx"
tex_mrao="PineappleGlasses_MRAO.ktx"
